### ISSUE TITLE
Tag a version to make a release

### ISSUE THREAD

**Issue by cdlm** [BlackFoundryCom/InriaFonts#1]
Hi, I've submitted a cask for the fonts: https://github.com/caskroom/homebrew-fonts/pull/1481

Tagging a release in this repo would make it possible to checksum the files and to auto-update the cask when you release an update.

**Comment by BlackFoundry** [comment]
tagged "InitialRelease"

**Comment by cdlm** [comment]
Thanks ! That helps with checksumming because I can point to a fixed version. However, the [github docs](https://help.github.com/articles/creating-releases/) recommend following [semantic versioning](https://semver.org). This is so that the tag is machine-readable. In the font metadata, I see version is 1.0 for serif and 1.200 for sans, so I'd suggest using something like `v1.200` for the tag (and versioning both sans and serif with the same higher number next time you fix something).
